"use client";
import { useState, useMemo } from "react";

export default function Home() {
  const [cari, setCari] = useState("");

  // DAFTAR DATA SISWA LENGKAP
  const semuaSiswa = [
    { nama: "ABID DWI SAPUTRA", kelas: "9A" },
    { nama: "AISYAH ENGGAR WIGATININGRUM", kelas: "9A" },
    { nama: "ALFIN RIZKY PUTRA PERDANA", kelas: "9A" },
    { nama: "ANDI PRATAMA", kelas: "9A" },
    { nama: "ARYANI ATTA NINDIA", kelas: "9A" },
    { nama: "ASYIFA FASILATUN NISA AFTAR", kelas: "9A" },
    { nama: "AZAHRA RAHMATUNISA", kelas: "9A" },
    { nama: "AZZAM AMMAR DANISH", kelas: "9A" },
    { nama: "CHAEZAR ARDU RAJJA", kelas: "9A" },
    { nama: "CINTA KHANZA AZALEA", kelas: "9A" },
    { nama: "DAVID YUDA SAPUTRA", kelas: "9A" },
    { nama: "DESTA RISKY PRITAMA", kelas: "9A" },
    { nama: "FRANDA GRESILIA ALFRIZA PUTRI", kelas: "9A" },
    { nama: "ILHAM DWI SAPUTRA", kelas: "9A" },
    { nama: "INDRA BAGUS RAHMATYO", kelas: "9A" },
    { nama: "KALISA VEXIA LUTVIANINGRUM", kelas: "9A" },
    { nama: "KEYLA KHOIRUN NISA'", kelas: "9A" },
    { nama: "KRISTA PRATAMA PEDROSA", kelas: "9A" },
    { nama: "LETHICIA DHEA AYU CANTIKA", kelas: "9A" },
    { nama: "MUH. MAHENDRA ARYA PUTRA PRATAMA", kelas: "9A" },
    { nama: "MUHAMMAD REZA SYAHPUTRA", kelas: "9A" },
    { nama: "NICHOLA REZA SAPUTRA", kelas: "9A" },
    { nama: "NOVELIA ZAHRO UMAYRAH", kelas: "9A" },
    { nama: "PUTRA ALIF TRISTA", kelas: "9A" },
    { nama: "RAHMAT TARNUDIANTO", kelas: "9A" },
    { nama: "RICO AL GHOZALI", kelas: "9A" },
    { nama: "RIZKY PURNOMO", kelas: "9A" },
    { nama: "RIZKY SYAMSUDIN RAHARJO", kelas: "9A" },
    { nama: "SALMA SETYO FITRIANI PUTRI", kelas: "9A" },
    { nama: "SATRIYA BINTANG NOR CAHYA", kelas: "9A" },
    { nama: "SILVIA DWI ANGGRAINI", kelas: "9A" },
    { nama: "ABDUL HAMID MUHAMAD YUSUP", kelas: "9B" },
    { nama: "ABDUL RAIS", kelas: "9B" },
    { nama: "ADITYA OCTAVIANO", kelas: "9B" },
    { nama: "AFTER MUHAMMAD GAMA", kelas: "9B" },
    { nama: "ALVINCENT AKSA WIJAYA", kelas: "9B" },
    { nama: "ANDRA PRATAMA WIJAYA", kelas: "9B" },
    { nama: "ANGGUN NURCAHAYATI", kelas: "9B" },
    { nama: "ARDAN TIRTA HARMAWAN", kelas: "9B" },
    { nama: "ARFA FAWWAZ ISWAHYUDI", kelas: "9B" },
    { nama: "AZARA RILIEF ISSARNO", kelas: "9B" },
    { nama: "BEIBY KHIRANA ROMADHONAH WIDYATMOKO", kelas: "9B" },
    { nama: "DIMAS RAFIE ARYASATYA", kelas: "9B" },
    { nama: "ENGGA NOH ALAMSYAH", kelas: "9B" },
    { nama: "FADHIL BAGUS PRAKOSO", kelas: "9B" },
    { nama: "FADLUN PERWIRA NATTA KHENZISHA", kelas: "9B" },
    { nama: "FERDINAND DONY ORLANDO", kelas: "9B" },
    { nama: "KEVIN TRIBUANA PAMUNGKAS", kelas: "9B" },
    { nama: "KEYLA PUTRI ANINDYA", kelas: "9B" },
    { nama: "KHOLIFAH WAHYU PUTRI", kelas: "9B" },
    { nama: "MEVRIL SADELA RAHMA", kelas: "9B" },
    { nama: "MOHAMMAD FAHRI KURNIAWAN", kelas: "9B" },
    { nama: "MUH RAFA XAVI AL HAKIM", kelas: "9B" },
    { nama: "NIKITA ANINDITA KURNIA RAMADHANI", kelas: "9B" },
    { nama: "NOVI DWI ANGGERI", kelas: "9B" },
    { nama: "NUR LAELA", kelas: "9B" },
    { nama: "RAKA BAGUS ADITYA SAPUTRA", kelas: "9B" },
    { nama: "TESAR RAMADHAN ADI NUGROHO", kelas: "9B" },
    { nama: "THAARIQ NUR WIDYAMANTO", kelas: "9B" },
    { nama: "TIARA DWI PRAWESTRI", kelas: "9B" },
    { nama: "ULUMMUDDIN BIRROHMAH", kelas: "9B" },
    { nama: "WAHYU DELLA SAFIRA", kelas: "9B" },
    { nama: "ZARRA AYU PUTRI GUMILAR", kelas: "9B" },
    { nama: "ALBINO EKA RAMADHAN", kelas: "9C" },
    { nama: "ALFIAN REZA ALDHIANSYAH", kelas: "9C" },
    { nama: "ALFONSO RAFAEL TRI SAPUTRA", kelas: "9C" },
    { nama: "ANDIKA BAGASKARA", kelas: "9C" },
    { nama: "AWALUDIN RIZQY SYARIF MUSTHOFA", kelas: "9C" },
    { nama: "AZAQE AURELIO JOVELY KURNIAWAN", kelas: "9C" },
    { nama: "BAGAS SURYO PRAKOSO", kelas: "9C" },
    { nama: "BENING AYUMAS HARTOTO", kelas: "9C" },
    { nama: "BRIAN KIYOSHI", kelas: "9C" },
    { nama: "DEWI VEGA VEBRIYANA", kelas: "9C" },
    { nama: "DZAKY ADIJAYA", kelas: "9C" },
    { nama: "FAFIAN ASWANGGA PRATAMA", kelas: "9C" },
    { nama: "FAJAR RESTU KURNIAWAN", kelas: "9C" },
    { nama: "GABRIEL PURNAMA", kelas: "9C" },
    { nama: "IKHSAN HAFIZ FAHTURAHMAN", kelas: "9C" },
    { nama: "KYANZA SHAFA NABILA", kelas: "9C" },
    { nama: "MUHAMMAD DINO RIZKYANTO", kelas: "9C" },
    { nama: "NAFISYA EGITA QURAINI", kelas: "9C" },
    { nama: "NATASYA NIFTAHUL JANAH", kelas: "9C" },
    { nama: "NOVAL PUTRA PRATAMA", kelas: "9C" },
    { nama: "NURUL HAMIDAH", kelas: "9C" },
    { nama: "RADITYA GALANG PRADANA", kelas: "9C" },
    { nama: "RAFA ADITYA PRADANA PUTRA", kelas: "9C" },
    { nama: "SHELOMITA NUR LINTANG", kelas: "9C" },
    { nama: "TORIQ HASAN SAFEI", kelas: "9C" },
    { nama: "YUNIOR CESAR KARIM ARDANA", kelas: "9C" },
    { nama: "ZAHDA IDAM ANGGARA", kelas: "9C" },
    { nama: "ALICE RINTAN NABILA", kelas: "9D" },
    { nama: "ANGGITO PUTRA CIPTANING", kelas: "9D" },
    { nama: "ARFIAN MUHAMMAD NUR ROHMAN", kelas: "9D" },
    { nama: "ARIZQI HASNAN MAULANA", kelas: "9D" },
    { nama: "BAGAS FEBRIAN SAPUTRA", kelas: "9D" },
    { nama: "BARRI KHOIRUL AZZAM", kelas: "9D" },
    { nama: "BAYU ANDI PAMUNGKAS", kelas: "9D" },
    { nama: "DESTIFA RICHANA HANINDIYA", kelas: "9D" },
    { nama: "DIMAS AGENG IRSYAD", kelas: "9D" },
    { nama: "FAJAR HUDA MUSTAQIM", kelas: "9D" },
    { nama: "FATIMAH INTAN SARI", kelas: "9D" },
    { nama: "FITRAH RIZQI RAMADHAN", kelas: "9D" },
    { nama: "GIRI PUTRA UTAMA", kelas: "9D" },
    { nama: "GIWANG RESTU FADILAH", kelas: "9D" },
    { nama: "HAFIZ DAFFA PRAYOGA", kelas: "9D" },
    { nama: "KARINA PUTRI KUSUMA DEWI", kelas: "9D" },
    { nama: "LINTANG ADHWA PUTRA SHANSI", kelas: "9D" },
    { nama: "M RAYHAN PUTRA MAHENDRA", kelas: "9D" },
    { nama: "MARVEL ADITYA PRATAMA", kelas: "9D" },
    { nama: "MAULANA ARIEF AL HAFIDZ", kelas: "9D" },
    { nama: "MUHAMMAD DUA RAMADHAN", kelas: "9D" },
    { nama: "MUHAMMAD FERNANDO ANINDYAGUNA", kelas: "9D" },
    { nama: "MUHAMMAD NAUFAL RIFQI", kelas: "9D" },
    { nama: "MUHAMMAD SYAFIQ", kelas: "9D" },
    { nama: "NDARU TRI REJEKI", kelas: "9D" },
    { nama: "PUTRI ASYA PERDANA", kelas: "9D" },
    { nama: "SANIYA NUR ALLITA", kelas: "9D" },
    { nama: "SAVA CALLISTA ROHMANA", kelas: "9D" },
    { nama: "SHAFIYAH NUR KHADIJAH", kelas: "9D" },
    { nama: "TESA AYU WULANDARI", kelas: "9D" },
    { nama: "TIYAN BAGUS PRASETYO", kelas: "9D" },
    { nama: "TYAS RIYADI", kelas: "9D" },
    { nama: "ALQIANO PUTRA HARIONO", kelas: "9E" },
    { nama: "AMINAH SULISTYANI UTAMI", kelas: "9E" },
    { nama: "ANDANG NUR ISNADI", kelas: "9E" },
    { nama: "ARISTA ESA PUTRA", kelas: "9E" },
    { nama: "BELLA CITRA ATMAJA", kelas: "9E" },
    { nama: "BENI PRIMA RIYANTO", kelas: "9E" },
    { nama: "BENITA CITRA APRILIA", kelas: "9E" },
    { nama: "CALVIN RIZKIFANI HARYONO", kelas: "9E" },
    { nama: "DANU RIDHO PRATAMA", kelas: "9E" },
    { nama: "DEWI SINTA", kelas: "9E" },
    { nama: "FARIKH ARRIZAL", kelas: "9E" },
    { nama: "FATQURRAHMAN WIJI NUGROHO", kelas: "9E" },
    { nama: "KIRANA NURENDRA DUHITA", kelas: "9E" },
    { nama: "MARIA FIDELIA NADINE CHIKA MIEDY", kelas: "9E" },
    { nama: "MOCHAMMAD ZIDANE PRASETIYONO", kelas: "9E" },
    { nama: "MUHAMMAD NUR FAUZI", kelas: "9E" },
    { nama: "MUHAMMAD RISKI OKTAVIANO", kelas: "9E" },
    { nama: "NABILA NUR ISTIQOMAH", kelas: "9E" },
    { nama: "NOVITA AULIA ARUM SARI", kelas: "9E" },
    { nama: "PUTRA BANGKIT SANJAYA WASITO", kelas: "9E" },
    { nama: "RAFIF DZAKY RAFAEL", kelas: "9E" },
    { nama: "RANGGA ADITIA PERMANA", kelas: "9E" },
    { nama: "RENDY BAGUS IRAWAN", kelas: "9E" },
    { nama: "RICO YAHYA MAULANA", kelas: "9E" },
    { nama: "RIDHO", kelas: "9E" },
    { nama: "RUSDIANA MAYA WULANDARI", kelas: "9E" },
    { nama: "SELVARA AGRISYA ZERLINDA", kelas: "9E" },
    { nama: "SISKA DWI HANDAYANI", kelas: "9E" },
    { nama: "TRI FAJAR JULIANO", kelas: "9E" },
    { nama: "VANESHA DWI INDAH ROCHMAH", kelas: "9E" },
    { nama: "WELLDAN PUTRA FAXZINDRA", kelas: "9E" },
    { nama: "WISNU KAUTSAR NAGORI HARAHAP", kelas: "9E" },
    { nama: "ADAM ELDA FERDANIANTO PUTRA", kelas: "8A" },
    { nama: "ALDIANSYAH RAMDHANI", kelas: "8A" },
    { nama: "ALIZZA AYU PUJI RAHMAWATI", kelas: "8A" },
    { nama: "ANNISA SHOLAIQA", kelas: "8A" },
    { nama: "AZIZ PRASETYA UTAMA", kelas: "8A" },
    { nama: "BELINDA AZARIA SALSABILA", kelas: "8A" },
    { nama: "BIMA OKTAVIO PURNOMO", kelas: "8A" },
    { nama: "CANNAVARO DAFFA PUTRA WIJAYA", kelas: "8A" },
    { nama: "DENDI HENDRAWAN", kelas: "8A" },
    { nama: "DESCA YULIA PUTRI", kelas: "8A" },
    { nama: "DEVITA PUTRI YADI", kelas: "8A" },
    { nama: "DIPHDA RAMADHANTI SUSANTO", kelas: "8A" },
    { nama: "HAMDAN SUKROH", kelas: "8A" },
    { nama: "HANNA ORIANA ZAFIRA", kelas: "8A" },
    { nama: "HAZRIEL GIBRAN ANANTA", kelas: "8A" },
    { nama: "ISEL NUR LILIANI", kelas: "8A" },
    { nama: "JASMIGO SYAHWA NUGRAHA", kelas: "8A" },
    { nama: "KEANU MEILANO TEGAR HERPAVI", kelas: "8A" },
    { nama: "KENZIE YUDHA HERMAWAN", kelas: "8A" },
    { nama: "KINGKIN ROSIANA DEWI", kelas: "8A" },
    { nama: "KISRI WENINGTYAS VEKTORIA", kelas: "8A" },
    { nama: "MEHRICHI NUR CALLYSTA", kelas: "8A" },
    { nama: "MUHAMMAD ALIF PRATAMA", kelas: "8A" },
    { nama: "MUHAMMAD GALIH ARRASYID", kelas: "8A" },
    { nama: "NOVI DARYANTI", kelas: "8A" },
    { nama: "RAVA ADITYA PUTRA ANANDA", kelas: "8A" },
    { nama: "REVAN ALDIANSYAH", kelas: "8A" },
    { nama: "RICO PUTRA SUGIARTO", kelas: "8A" },
    { nama: "SAFA AURA NINGTIYAS", kelas: "8A" },
    { nama: "SATRIYANDRA WASKITO PUTRA RAJABA", kelas: "8A" },
    { nama: "VIOLA YUNITA BASTIAN", kelas: "8A" },
    { nama: "ALFANO EZA SANTOSO", kelas: "8B" },
    { nama: "ARGA ADIPUTRA PRATAMA", kelas: "8B" },
    { nama: "ARJUNA SATRIA SUSILO", kelas: "8B" },
    { nama: "AURA BIDADARI ANGIN TIMUR", kelas: "8B" },
    { nama: "AZZAHRA AFIFAH NADIF", kelas: "8B" },
    { nama: "BIMA ARYADI", kelas: "8B" },
    { nama: "DENISH ZAHEENWAR", kelas: "8B" },
    { nama: "DESFITA BELA ANGGRAINI", kelas: "8B" },
    { nama: "DEVANDRA RAGIL MAULANA", kelas: "8B" },
    { nama: "DEWARI DION SHOLEKHAH", kelas: "8B" },
    { nama: "DHEWANDARI DION SHOLEHAH", kelas: "8B" },
    { nama: "DIRA ADELIA AGATHA", kelas: "8B" },
    { nama: "DZAKY NINO RAMADHAN", kelas: "8B" },
    { nama: "EWALDO NUR KRISTANTO", kelas: "8B" },
    { nama: "FANEZA DELLA MARSELA", kelas: "8B" },
    { nama: "GALANG ANDRIAN PUTRA PERMATA", kelas: "8B" },
    { nama: "JESICHA OCTAVIANI WULANDARI", kelas: "8B" },
    { nama: "JOANEVANO CAESA WICAKSONO", kelas: "8B" },
    { nama: "JOVITA AMORA DILES", kelas: "8B" },
    { nama: "KAHFIO REZKYADI", kelas: "8B" },
    { nama: "KAIFAH KANSA SOLEKAH", kelas: "8B" },
    { nama: "KHANSA KHAIRUNNISA", kelas: "8B" },
    { nama: "KIRANA PUTRI MAHARDIKA", kelas: "8B" },
    { nama: "MAYA LIDWINA AMBARSARI", kelas: "8B" },
    { nama: "MUHAMMAD KHAREL NASUHA", kelas: "8B" },
    { nama: "MUHAMMAD SYAHRAFI AFIANTO", kelas: "8B" },
    { nama: "NAYLA ASHIFFA SUTAPA", kelas: "8B" },
    { nama: "NUR ALISHA FARHA", kelas: "8B" },
    { nama: "PUTRI AYUNINGTYAS", kelas: "8B" },
    { nama: "RABBANI NATHAN QASIRU SAKTI", kelas: "8B" },
    { nama: "VALENTINO DEVAN KRISTIAWAN", kelas: "8B" },
    { nama: "ADITYA RANGGA SAPUTRA", kelas: "8C" },
    { nama: "AISSA NUR HIDAYAH", kelas: "8C" },
    { nama: "ALTHAKHANSAA IZZNUR KAILANI", kelas: "8C" },
    { nama: "ALVANDA HANISA MAY SHOLIKAH", kelas: "8C" },
    { nama: "ARFANDI GHAISAN ARIFIN", kelas: "8C" },
    { nama: "ARYASUTA ADI PRADANA", kelas: "8C" },
    { nama: "BAGAS FATKHURROHMAN", kelas: "8C" },
    { nama: "BINTANG DAMAI PUTRIANI", kelas: "8C" },
    { nama: "CHRISTINA NATALIA PAKPAHAN", kelas: "8C" },
    { nama: "DARREN KRESNO WIBOWO", kelas: "8C" },
    { nama: "ERIZKI AGUS MEY BELLA", kelas: "8C" },
    { nama: "FAKHRUL ARIFIN AL ALIM", kelas: "8C" },
    { nama: "GALANG YUDHO WICAKSONO", kelas: "8C" },
    { nama: "GRACE NUR KRISTANTO", kelas: "8C" },
    { nama: "JOHAN BAYU PRATAMA", kelas: "8C" },
    { nama: "LAZUARDI RAYHANUN", kelas: "8C" },
    { nama: "LEONARDO FEBRY WIJAYA", kelas: "8C" },
    { nama: "LETICIA NAYA DJAMI", kelas: "8C" },
    { nama: "LUNETTA ARDINE", kelas: "8C" },
    { nama: "MUHAMMAD ABID JANUDIN", kelas: "8C" },
    { nama: "MUHAMMAD FADLI MAULANA", kelas: "8C" },
    { nama: "NOVERRA AYUNDA WARDANA", kelas: "8C" },
    { nama: "RAFFIQI HAKEM", kelas: "8C" },
    { nama: "RARA MUTIARA", kelas: "8C" },
    { nama: "RENO HAFIS WIJAYADI", kelas: "8C" },
    { nama: "RIFQI MADYA PUTRA", kelas: "8C" },
    { nama: "SKOLASTIKA KEISHA ARLEEN GRISELDA", kelas: "8C" },
    { nama: "THERESIA SEKAR ADI KUS WIJAYANTI", kelas: "8C" },
    { nama: "VANO RIZKY SAPUTRA", kelas: "8C" },
    { nama: "ADAM JATY WIGUNA", kelas: "8D" },
    { nama: "AKBAR RIZKHI WIJANAKA", kelas: "8D" },
    { nama: "ALEXANDER LORENZO", kelas: "8D" },
    { nama: "ANNISA RAHMI WARDANA", kelas: "8D" },
    { nama: "ARYA ARJUNA SETA", kelas: "8D" },
    { nama: "AYU ADINDA RAH FAIZA", kelas: "8D" },
    { nama: "AZRA DESTRIANA PUTRI BOKARI", kelas: "8D" },
    { nama: "BAGUS UNGGUL NARENDRA WIBISANA", kelas: "8D" },
    { nama: "CAHAYA QURROTA A'YUNI AHSANULHAQ", kelas: "8D" },
    { nama: "DEWI SASKIA NUR CAHYATI", kelas: "8D" },
    { nama: "DINA SELVIANA", kelas: "8D" },
    { nama: "DIYAH PUTRI WULANDARI", kelas: "8D" },
    { nama: "ERIKA DESI SENIA PUTRI", kelas: "8D" },
    { nama: "EVIELLIA TRISNA NUR KHASANAH", kelas: "8D" },
    { nama: "GEA SEKAR SARI", kelas: "8D" },
    { nama: "KINAYA SALSABILA LARASATI MADI", kelas: "8D" },
    { nama: "LUCKY SATRIA PERMANA", kelas: "8D" },
    { nama: "M. ALIF NUR ZIDAN", kelas: "8D" },
    { nama: "MUHAMMAD UMAR LUTHFIANSYAH", kelas: "8D" },
    { nama: "MUTIARA DWI ASTUTI", kelas: "8D" },
    { nama: "NALENDRA BHANU TIRTA HERMANU", kelas: "8D" },
    { nama: "NAURA CHANTIKA FITRI DWIYANTI", kelas: "8D" },
    { nama: "NDARU AL FARUQ", kelas: "8D" },
    { nama: "NINDYTA CLARINA PUTRI", kelas: "8D" },
    { nama: "RADIT PUTRA ARYA", kelas: "8D" },
    { nama: "RAMADHAN ANGGARA", kelas: "8D" },
    { nama: "REIHAN HAZIM KAILANI", kelas: "8D" },
    { nama: "RISKY PUTRA SETYA NUGRAHA", kelas: "8D" },
    { nama: "SHELLIE MAESYAROH", kelas: "8D" },
    { nama: "SUJJEDAN FERSARIANO SUTBISAL", kelas: "8D" },
    { nama: "VEGANIA SAFIRA DWI SAFITRI", kelas: "8D" },
    { nama: "YOGA SETIAWAN", kelas: "8D" },
    { nama: "AFIF NAUFAL", kelas: "8E" },
    { nama: "AIZAHRA AURA KHANZA", kelas: "8E" },
    { nama: "ANDINI KYRA ZIVANKA", kelas: "8E" },
    { nama: "ANGGI AYU WULANDARI", kelas: "8E" },
    { nama: "APRILIA SURYA LARAS WATI", kelas: "8E" },
    { nama: "APRILIO DWI WARDANA", kelas: "8E" },
    { nama: "ARDHIKA NANDA OCTAVINO", kelas: "8E" },
    { nama: "ARVINA ACTAVIA YUINDA", kelas: "8E" },
    { nama: "ASYA SAPUTRI", kelas: "8E" },
    { nama: "ATHA CHOIRUL AJI PANGESTU", kelas: "8E" },
    { nama: "AXEL ARDISTIAN", kelas: "8E" },
    { nama: "BAGUS MAULANA", kelas: "8E" },
    { nama: "DESTA MAULANA GI FAHRI", kelas: "8E" },
    { nama: "FAREL ARDIANSYAH PRATAMA", kelas: "8E" },
    { nama: "FARIDHIEN ASHRAFUL AULIA", kelas: "8E" },
    { nama: "GALUH SEPTI SETIAWATI", kelas: "8E" },
    { nama: "INTANAYLA GIANDANI", kelas: "8E" },
    { nama: "JOVAN PRASETIO", kelas: "8E" },
    { nama: "LATIFAH DWI ARTIKAHUSNA", kelas: "8E" },
    { nama: "MAULANA DANU SAPUTRA", kelas: "8E" },
    { nama: "MAULANA YOGI KURNIAWAN", kelas: "8E" },
    { nama: "NAILA ANANDITYA", kelas: "8E" },
    { nama: "NITA ASMA WATI", kelas: "8E" },
    { nama: "OKTAVIANO RIDHO PRASETYA", kelas: "8E" },
    { nama: "PUPUT ANGGRAINI", kelas: "8E" },
    { nama: "PUTRI ANA SILFILIANI", kelas: "8E" },
    { nama: "REFAN RIZKI GUNAWAN", kelas: "8E" },
    { nama: "REVAN SAPUTRA", kelas: "8E" },
    { nama: "RIZKY TRI SETIAWAN", kelas: "8E" },
    { nama: "SHIFA AYU ANGGRAINI", kelas: "8E" },
    { nama: "TITANIA ALMIRA WIDARTO", kelas: "8E" },
    { nama: "ZAKKY PUTRA MAULANA", kelas: "8E" },
    { nama: "ZONA OGY TRI AFFANDI", kelas: "8E" },
    { nama: "ANDHIKA PUTRA PRATAMA", kelas: "7A" },
    { nama: "BINTANG JULIAN ANUGERAH", kelas: "7A" },
    { nama: "BINTANG TAKSAKA HARUNA PUTRA", kelas: "7A" },
    { nama: "BUKHORI NUR ABROR", kelas: "7A" },
    { nama: "DAFFA DZAKY ANUGRAH", kelas: "7A" },
    { nama: "DINA WINDI OKTAVIANA", kelas: "7A" },
    { nama: "FADHIL LINTANG PRASETYO", kelas: "7A" },
    { nama: "FITNAH RAMADANI", kelas: "7A" },
    { nama: "GALAN SATRIA LANTANG", kelas: "7A" },
    { nama: "GALIH WIRATAMA", kelas: "7A" },
    { nama: "JESICA NASYWA MAHARANI", kelas: "7A" },
    { nama: "KAYLA MIKHA AQUINA", kelas: "7A" },
    { nama: "MUHAMAD ZIAN PURNAMA", kelas: "7A" },
    { nama: "MUHAMMAD LUTHFI TSANY", kelas: "7A" },
    { nama: "MUHAMMAD NIAM", kelas: "7A" },
    { nama: "NAFIA ILMA ARSYANI", kelas: "7A" },
    { nama: "NAYA SALSABILLA", kelas: "7A" },
    { nama: "NOR AYU MUSTIKA YOHANA", kelas: "7A" },
    { nama: "RAISA NANDA KIRANA", kelas: "7A" },
    { nama: "RESCY WAHYU WIDIHERMANTO", kelas: "7A" },
    { nama: "RIZKY PUTRA EKSAN RAMADHANI", kelas: "7A" },
    { nama: "RIZKY PUTRA PRATAMA", kelas: "7A" },
    { nama: "SADEWA CANDRA WIJAYA PUTRA", kelas: "7A" },
    { nama: "SALSABILLA AYU DEWI", kelas: "7A" },
    { nama: "SANY MARTCHA MEDIANTO", kelas: "7A" },
    { nama: "SASKIA NOVIKA PUTRI", kelas: "7A" },
    { nama: "SYANDANA RIZKI NARARYA", kelas: "7A" },
    { nama: "TARA VANESHA ELANO", kelas: "7A" },
    { nama: "TAUFIQ AZIZ ADZ DZIKRI", kelas: "7A" },
    { nama: "ADITYA BAGUS RAHARDIAN", kelas: "7B" },
    { nama: "AFRIZAL DEKA PRADITA", kelas: "7B" },
    { nama: "AKBAR ARDIANSYAH", kelas: "7B" },
    { nama: "ALIF RAMDHANI", kelas: "7B" },
    { nama: "ANATASYA NOVALIA DEWANTARA", kelas: "7B" },
    { nama: "ARVINO ZAKIA RAMADHANNU", kelas: "7B" },
    { nama: "AZZAHRA AULIANA KAFFAH", kelas: "7B" },
    { nama: "BIMA CAHYA RAMADHAN", kelas: "7B" },
    { nama: "CANTIKA DYAH MUSTIKA WATI", kelas: "7B" },
    { nama: "DAFFA NUGISA WIRATAMA", kelas: "7B" },
    { nama: "DANIAR AKSHA PUTRA FEBRIAN", kelas: "7B" },
    { nama: "DIMAS ARDIAN SAPUTRA", kelas: "7B" },
    { nama: "FAISHAL DWI SYAHPUTRA", kelas: "7B" },
    { nama: "FITRIANA RAHMAWATI", kelas: "7B" },
    { nama: "KHAIRUNNISA ALYAA RAMADHANI", kelas: "7B" },
    { nama: "MUHAMMAD NURUL HUDA", kelas: "7B" },
    { nama: "NAFILA ZALFA DHEA ZAHIRA", kelas: "7B" },
    { nama: "NURZANAH DWI SUSILOWATI", kelas: "7B" },
    { nama: "OVI NAJWA MARWA", kelas: "7B" },
    { nama: "RAHESYA PUTRA ARYANA", kelas: "7B" },
    { nama: "REINA AHZA MAULIDA", kelas: "7B" },
    { nama: "RIDWAN ATSNAN FAQIHUDDIN", kelas: "7B" },
    { nama: "RIFAT NAUFAL HIDAYATULLAH", kelas: "7B" },
    { nama: "RIO AKBAR ADI SAPUTRA", kelas: "7B" },
    { nama: "RIZQY FEBRIANO", kelas: "7B" },
    { nama: "RYAN ADITYA", kelas: "7B" },
    { nama: "SATRIO YOKA", kelas: "7B" },
    { nama: "SAVIRA PUTRI RAMADANI", kelas: "7B" },
    { nama: "SHAFA NINDYA AZ ZAHRA", kelas: "7B" },
    { nama: "ALEXANDRIA ALICE QINA GEVRILA", kelas: "7C" },
    { nama: "ARIEF RIZKY", kelas: "7C" },
    { nama: "BENEDIKTUS RENO ADITYA", kelas: "7C" },
    { nama: "CLEVERY ALMA NURHUDA", kelas: "7C" },
    { nama: "DENIAS WANDAGAU", kelas: "7C" },
    { nama: "DEVIKA AIRA SYAHPUTRI", kelas: "7C" },
    { nama: "EVIN RAMADHANI", kelas: "7C" },
    { nama: "FADIAS RISKY PRATAMA", kelas: "7C" },
    { nama: "FAIS SEPTIAN RADITYA PRATAMA", kelas: "7C" },
    { nama: "FATHAN NUR RAHMAN", kelas: "7C" },
    { nama: "FIONA IRENE KRISTIJOADI", kelas: "7C" },
    { nama: "GREGORIUS SIENE JAGAD MAHADEWA", kelas: "7C" },
    { nama: "HAZIEL FILBERT CARLENE ARELI PUTRA", kelas: "7C" },
    { nama: "ISYAILLAROSE NAURA SYAILENDRA", kelas: "7C" },
    { nama: "KUSUMA BAGUS ASMARA JATI", kelas: "7C" },
    { nama: "MEDIANA SIVA PURWANINGSIH", kelas: "7C" },
    { nama: "MEYLA JASMIN", kelas: "7C" },
    { nama: "NAUFAL GIBRAN WIRAWAN", kelas: "7C" },
    { nama: "NICOLAUS ALDY RIZKI SYAHPUTRA", kelas: "7C" },
    { nama: "NOVELLIA AZZAHRA PUTRI", kelas: "7C" },
    { nama: "QUEEN NEW DINANTIKU", kelas: "7C" },
    { nama: "RAFA RADIKA HERMANSYAH", kelas: "7C" },
    { nama: "RAGIL TRI SAPUTRO", kelas: "7C" },
    { nama: "RAHMAT NUGROHO", kelas: "7C" },
    { nama: "RIDHO AMANTA", kelas: "7C" },
    { nama: "RINES CASSIEL AMORA", kelas: "7C" },
    { nama: "SHAWA MARTA PRASETYA", kelas: "7C" },
    { nama: "SPARTAN KURNIA PAMUNGKAS", kelas: "7C" },
    { nama: "YOURA NAYARA AKILA ZAHRA", kelas: "7C" },
    { nama: "ZAKY KHOIRUDIN", kelas: "7C" },
    { nama: "ADITIYA OKI YULIYANTO", kelas: "7D" },
    { nama: "AFIQAH MIKHAYLA AYODYA", kelas: "7D" },
    { nama: "ALIYA THALITA WULANDARI", kelas: "7D" },
    { nama: "ALODYA ANABELLA", kelas: "7D" },
    { nama: "ALVARO INDRA PRATAMA", kelas: "7D" },
    { nama: "ARGA NOVA SYAH PUTRA", kelas: "7D" },
    { nama: "AZ-ZAHRA MULYA", kelas: "7D" },
    { nama: "AZZANA KHARISMA PUTRI", kelas: "7D" },
    { nama: "BANYU BIRU", kelas: "7D" },
    { nama: "CINDY KUSUMA PUTRI", kelas: "7D" },
    { nama: "DEFANDA PUTRA PRASETYA", kelas: "7D" },
    { nama: "DHEVAN HABIB MAULANA PUTRA", kelas: "7D" },
    { nama: "EKSA BAGAS RAMMADHANI", kelas: "7D" },
    { nama: "FADLY ARYA PUTRA", kelas: "7D" },
    { nama: "HENDRIANSAH", kelas: "7D" },
    { nama: "ITA RAHMAWATI", kelas: "7D" },
    { nama: "MAYUSA LUPPI IRADILA", kelas: "7D" },
    { nama: "MUH. AFRAYKHAN RAHARDIKA", kelas: "7D" },
    { nama: "MUHAMMAD FAQIH ALIFINO", kelas: "7D" },
    { nama: "MUHAMMAD IRSYAD NUR FALAH", kelas: "7D" },
    { nama: "MUTIARA NOVI ANGGITA", kelas: "7D" },
    { nama: "NABIL DAIVA ARVA", kelas: "7D" },
    { nama: "NASAFA DESTIAN MAISAROH", kelas: "7D" },
    { nama: "NEISYA AIRIFANNA", kelas: "7D" },
    { nama: "REVANEO ZIDHAN KUSUMA", kelas: "7D" },
    { nama: "SALWAA NUR ROHMAN", kelas: "7D" },
    { nama: "SUNGSANG RAHAYU", kelas: "7D" },
    { nama: "TEGAR AL ROHMAT", kelas: "7D" },
    { nama: "TISA IFTIANI", kelas: "7D" },
    { nama: "ZALUNA AQIELA ZAHWA", kelas: "7D" },
    { nama: "ADEL ANGGITA SARI", kelas: "7E" },
    { nama: "ALFIN SAPUTRA", kelas: "7E" },
    { nama: "AQILA AMELIA DANI", kelas: "7E" },
    { nama: "ASKA DEVANO PRABOWO", kelas: "7E" },
    { nama: "AZWA AZZAHRA", kelas: "7E" },
    { nama: "BELLA PURPITASARI", kelas: "7E" },
    { nama: "BIMA ASMARA", kelas: "7E" },
    { nama: "DEANDRA ADE PRATAMA", kelas: "7E" },
    { nama: "DESTY ANGGITA SARI", kelas: "7E" },
    { nama: "EGA NUR RAHMAN", kelas: "7E" },
    { nama: "EKA RAMADHANIA", kelas: "7E" },
    { nama: "EVAN KIKIFANI HARYONO", kelas: "7E" },
    { nama: "FAFAY NUR AULIA WIWAHA", kelas: "7E" },
    { nama: "FAIZA NUR ZULHI", kelas: "7E" },
    { nama: "HENY DWI RAHMAWATI", kelas: "7E" },
    { nama: "KAEYZA AZZAHRA ERLYANO", kelas: "7E" },
    { nama: "KEISHA PUTRI UMAIRAH", kelas: "7E" },
    { nama: "KRISTIAN REVAN ARDENA", kelas: "7E" },
    { nama: "MADA IBRAHIM", kelas: "7E" },
    { nama: "MANUEL FIANDRA SAKA AMORIDESTA", kelas: "7E" },
    { nama: "MUHAMAD FAIRUZ JUSTIN", kelas: "7E" },
    { nama: "NARAYA RISKIKA HERDIAS", kelas: "7E" },
    { nama: "RAJA DIRGANTARA", kelas: "7E" },
    { nama: "REVAN DWI WICAKSANA", kelas: "7E" },
    { nama: "REVIANO NUGRAHA", kelas: "7E" },
    { nama: "SIFA SAFIRA", kelas: "7E" },
    { nama: "SYIFA NUR AINI", kelas: "7E" },
    { nama: "VINDA CHAYYIRA", kelas: "7E" },
    { nama: "VREZA ALFIAN MAULANA", kelas: "7E" },
    { nama: "ZIDANE ANDROMEDA PUTRA", kelas: "7E" },
  ];

  const daftarTersaring = useMemo(() => {
    return semuaSiswa.filter((s) =>
      s.nama.toLowerCase().includes(cari.toLowerCase()) || 
      s.kelas.toLowerCase().includes(cari.toLowerCase())
    );
  }, [cari]);

  return (
    <div className="min-h-screen bg-slate-50 pb-28">
      {/* Header & Search Bar */}
      <div className="sticky top-0 bg-blue-900 p-4 shadow-2xl z-50">
        <h1 className="text-white text-center font-black text-xl mb-4">E-PRESENSI SMP 2026</h1>
        <div className="relative max-w-xl mx-auto">
          <input 
            type="text"
            placeholder="Ketik Nama atau Kelas (misal: 9A)..."
            className="w-full p-4 rounded-2xl shadow-inner outline-none text-lg font-bold border-none"
            value={cari}
            onChange={(e) => setCari(e.target.value)}
          />
          {cari && (
            <button 
              onClick={() => setCari("")}
              className="absolute right-4 top-4 text-gray-400 font-bold"
            >
              X
            </button>
          )}
        </div>
      </div>

      <div className="max-w-xl mx-auto p-4">
        <div className="flex justify-between items-center mb-4 text-slate-500 font-bold text-[10px] uppercase px-2 tracking-widest">
          <span>Daftar Siswa</span>
          <span className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full">
            {daftarTersaring.length} Orang
          </span>
        </div>

        <div className="grid gap-3">
          {daftarTersaring.map((s, index) => (
            <div key={index} className="flex items-center justify-between bg-white p-4 rounded-2xl border border-slate-200 shadow-sm hover:border-blue-400 transition-colors">
              <div className="flex-1 pr-2">
                <div className="font-bold text-slate-800 uppercase text-xs sm:text-sm leading-tight">{s.nama}</div>
                <div className="text-[9px] font-black bg-blue-600 text-white px-2 py-0.5 rounded mt-1 inline-block italic uppercase">KELAS {s.kelas}</div>
              </div>
              <select className="bg-slate-100 border-2 border-slate-200 rounded-xl p-2 text-xs font-bold outline-none focus:border-blue-600 appearance-none">
                <option>✅ HADIR</option>
                <option>IZIN</option>
                <option>SAKIT</option>
                <option>ALPA</option>
              </select>
            </div>
          ))}
        </div>

        {daftarTersaring.length === 0 && (
          <div className="text-center py-20 text-slate-400 italic">Data tidak ditemukan...</div>
        )}
      </div>

      {/* Tombol Simpan Melayang */}
      <div className="fixed bottom-8 left-0 right-0 px-6 z-40">
        <button 
          onClick={() => alert("Laporan Presensi Berhasil Disimpan!")}
          className="w-full max-w-xl mx-auto block bg-green-600 text-white font-black py-5 rounded-3xl shadow-2xl text-lg uppercase tracking-widest active:scale-95 hover:bg-green-700 transition-all"
        >
          Simpan Laporan
        </button>
      </div>
    </div>
  );
}